- hosts: master
  become: true
  vars_files:
  - vars/login.yml
  - vars/instances.yml
  - vars/common_configuration.yml
  roles:
  - master
  
- hosts: workers
  become: true
  vars_files:
  - vars/login.yml
  - vars/instances.yml
  - vars/common_configuration.yml
  - vars/{{ ansible_default_ipv4.address }}.yml
  roles:
  - worker
  
